### ISSUE TITLE
holistic file does not exist

### ISSUE THREAD

**Issue by cobraheleah** [IBM/benchbench#3]
* bat version:0.1.0
* Python version:3.10.12
* Operating System:linux

### Description

In https://github.com/IBM/benchbench/blob/main/src/bat/utils.py#L7
it seems that the combined_holistic_20240708.csv file mentioned in this line of code does not exist.

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by perlitz** [comment]
Thanks for submitting the Issue, I'll make sure to fix it by Monday

**Comment by cobraheleah** [comment]
hello，has the code been updated?

**Comment by perlitz** [comment]
hi @cobraheleah 
sorry for that, the API has changed some
I will soon update the readme, in the meanwhile, check out the example: https://github.com/IBM/benchbench/blob/main/examples/newbench_example.py
I will not close the issue until the readme will be fixed

Thanks again

**Comment by perlitz** [comment]
The readme and example are fixed.
closing this issue, thanks again.
LMK if you need further help
